# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\dti_qa.ui'
#
# Created: Tue May 07 17:15:04 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class PreviewMouseClick(object):
    
    """Object passed when preview pane is leftclicked"""
    
    SLICING_AXIS = None
    EVENT = None
    
    def __init__(self, axis, event):
        self.EVENT = event
        self.SLICING_AXIS = axis

class PreviewQLabel(QtGui.QLabel):
    
    """Preview pane"""
    
    SLICING_AXIS = None
    
    def __init__(self, *args, **kwargs):
        if 'slicing_axis' in kwargs:
            self.SLICING_AXIS = kwargs['slicing_axis']
            del kwargs['slicing_axis']                      
        super(PreviewQLabel, self).__init__(*args, **kwargs)
    
    previewClicked = QtCore.pyqtSignal(PreviewMouseClick , name='previewClicked(QPoint)')
    
    def mousePressEvent(self, event):
        self.previewClicked.emit(PreviewMouseClick(self.SLICING_AXIS, event))
#         print event.pos().x(), event.pos().y(), type(event.pos())


class Ui_FormDTIQA(object):
    def setupUi(self, FormDTIQA):
        FormDTIQA.setObjectName(_fromUtf8("FormDTIQA"))
        FormDTIQA.resize(1024, 551)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FormDTIQA.sizePolicy().hasHeightForWidth())
        FormDTIQA.setSizePolicy(sizePolicy)
        FormDTIQA.setMaximumSize(QtCore.QSize(1024, 16777215))
        self.gridLayout = QtGui.QGridLayout(FormDTIQA)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.splitter = QtGui.QSplitter(FormDTIQA)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.groupBox_dataset = QtGui.QGroupBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_dataset.sizePolicy().hasHeightForWidth())
        self.groupBox_dataset.setSizePolicy(sizePolicy)
        self.groupBox_dataset.setMaximumSize(QtCore.QSize(16777215, 300))
        self.groupBox_dataset.setObjectName(_fromUtf8("groupBox_dataset"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_dataset)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splitter_3 = QtGui.QSplitter(self.groupBox_dataset)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.layoutWidget = QtGui.QWidget(self.splitter_3)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_nifti = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_nifti.sizePolicy().hasHeightForWidth())
        self.label_nifti.setSizePolicy(sizePolicy)
        self.label_nifti.setMinimumSize(QtCore.QSize(45, 37))
        self.label_nifti.setMaximumSize(QtCore.QSize(45, 37))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_nifti.setFont(font)
        self.label_nifti.setObjectName(_fromUtf8("label_nifti"))
        self.horizontalLayout_3.addWidget(self.label_nifti)
        self.lineEdit_nifti = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_nifti.setReadOnly(True)
        self.lineEdit_nifti.setObjectName(_fromUtf8("lineEdit_nifti"))
        self.horizontalLayout_3.addWidget(self.lineEdit_nifti)
        self.pushButton_nifti = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_nifti.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pushButton_nifti.setObjectName(_fromUtf8("pushButton_nifti"))
        self.horizontalLayout_3.addWidget(self.pushButton_nifti)
        self.layoutWidget1 = QtGui.QWidget(self.splitter_3)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_bvals = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_bvals.sizePolicy().hasHeightForWidth())
        self.label_bvals.setSizePolicy(sizePolicy)
        self.label_bvals.setMinimumSize(QtCore.QSize(45, 37))
        self.label_bvals.setMaximumSize(QtCore.QSize(45, 37))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_bvals.setFont(font)
        self.label_bvals.setObjectName(_fromUtf8("label_bvals"))
        self.horizontalLayout_4.addWidget(self.label_bvals)
        self.lineEdit_bvals = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_bvals.setReadOnly(True)
        self.lineEdit_bvals.setObjectName(_fromUtf8("lineEdit_bvals"))
        self.horizontalLayout_4.addWidget(self.lineEdit_bvals)
        self.pushButton_bvals = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_bvals.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pushButton_bvals.setObjectName(_fromUtf8("pushButton_bvals"))
        self.horizontalLayout_4.addWidget(self.pushButton_bvals)
        self.layoutWidget2 = QtGui.QWidget(self.splitter_3)
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_bvecs = QtGui.QLabel(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_bvecs.sizePolicy().hasHeightForWidth())
        self.label_bvecs.setSizePolicy(sizePolicy)
        self.label_bvecs.setMinimumSize(QtCore.QSize(45, 37))
        self.label_bvecs.setMaximumSize(QtCore.QSize(45, 37))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_bvecs.setFont(font)
        self.label_bvecs.setObjectName(_fromUtf8("label_bvecs"))
        self.horizontalLayout_5.addWidget(self.label_bvecs)
        self.lineEdit_bvecs = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_bvecs.setReadOnly(True)
        self.lineEdit_bvecs.setObjectName(_fromUtf8("lineEdit_bvecs"))
        self.horizontalLayout_5.addWidget(self.lineEdit_bvecs)
        self.pushButton_bvecs = QtGui.QPushButton(self.layoutWidget2)
        self.pushButton_bvecs.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pushButton_bvecs.setObjectName(_fromUtf8("pushButton_bvecs"))
        self.horizontalLayout_5.addWidget(self.pushButton_bvecs)
        self.layoutWidget3 = QtGui.QWidget(self.splitter_3)
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_loadedpath = QtGui.QLabel(self.layoutWidget3)
        self.label_loadedpath.setMaximumSize(QtCore.QSize(80, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_loadedpath.setFont(font)
        self.label_loadedpath.setObjectName(_fromUtf8("label_loadedpath"))
        self.horizontalLayout.addWidget(self.label_loadedpath)
        self.lineEdit_loadedpath = QtGui.QLineEdit(self.layoutWidget3)
        self.lineEdit_loadedpath.setEnabled(False)
        self.lineEdit_loadedpath.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_loadedpath.setReadOnly(True)
        self.lineEdit_loadedpath.setObjectName(_fromUtf8("lineEdit_loadedpath"))
        self.horizontalLayout.addWidget(self.lineEdit_loadedpath)
        self.commandLinkButton_load = QtGui.QCommandLinkButton(self.splitter_3)
        self.commandLinkButton_load.setEnabled(False)
        self.commandLinkButton_load.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setBold(True)
        font.setWeight(75)
        self.commandLinkButton_load.setFont(font)
        self.commandLinkButton_load.setObjectName(_fromUtf8("commandLinkButton_load"))
        self.verticalLayout.addWidget(self.splitter_3)
        self.groupBox_actions = QtGui.QGroupBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_actions.sizePolicy().hasHeightForWidth())
        self.groupBox_actions.setSizePolicy(sizePolicy)
        self.groupBox_actions.setMaximumSize(QtCore.QSize(225, 300))
        self.groupBox_actions.setObjectName(_fromUtf8("groupBox_actions"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_actions)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.splitter_2 = QtGui.QSplitter(self.groupBox_actions)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.layoutWidget4 = QtGui.QWidget(self.splitter_2)
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout_bvaluelabel = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_bvaluelabel.setMargin(0)
        self.horizontalLayout_bvaluelabel.setObjectName(_fromUtf8("horizontalLayout_bvaluelabel"))
        self.label_bvaluetitle = QtGui.QLabel(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_bvaluetitle.sizePolicy().hasHeightForWidth())
        self.label_bvaluetitle.setSizePolicy(sizePolicy)
        self.label_bvaluetitle.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_bvaluetitle.setFont(font)
        self.label_bvaluetitle.setObjectName(_fromUtf8("label_bvaluetitle"))
        self.horizontalLayout_bvaluelabel.addWidget(self.label_bvaluetitle)
        self.label_bvalue = QtGui.QLabel(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_bvalue.sizePolicy().hasHeightForWidth())
        self.label_bvalue.setSizePolicy(sizePolicy)
        self.label_bvalue.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_bvalue.setFont(font)
        self.label_bvalue.setText(_fromUtf8(""))
        self.label_bvalue.setObjectName(_fromUtf8("label_bvalue"))
        self.horizontalLayout_bvaluelabel.addWidget(self.label_bvalue)
        self.layoutWidget5 = QtGui.QWidget(self.splitter_2)
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalSlider_imageno = QtGui.QSlider(self.layoutWidget5)
        self.horizontalSlider_imageno.setEnabled(False)
        self.horizontalSlider_imageno.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_imageno.setObjectName(_fromUtf8("horizontalSlider_imageno"))
        self.horizontalLayout_2.addWidget(self.horizontalSlider_imageno)
        self.lcdNumber_imageno = QtGui.QLCDNumber(self.layoutWidget5)
        self.lcdNumber_imageno.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_imageno.sizePolicy().hasHeightForWidth())
        self.lcdNumber_imageno.setSizePolicy(sizePolicy)
        self.lcdNumber_imageno.setMaximumSize(QtCore.QSize(50, 25))
        self.lcdNumber_imageno.setObjectName(_fromUtf8("lcdNumber_imageno"))
        self.horizontalLayout_2.addWidget(self.lcdNumber_imageno)
        self.layoutWidget6 = QtGui.QWidget(self.splitter_2)
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_13.setMargin(0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.pushButton_exclude = QtGui.QPushButton(self.layoutWidget6)
        self.pushButton_exclude.setEnabled(False)
        self.pushButton_exclude.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pushButton_exclude.setObjectName(_fromUtf8("pushButton_exclude"))
        self.horizontalLayout_13.addWidget(self.pushButton_exclude)
        self.pushButton_clear = QtGui.QPushButton(self.layoutWidget6)
        self.pushButton_clear.setEnabled(False)
        self.pushButton_clear.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pushButton_clear.setObjectName(_fromUtf8("pushButton_clear"))
        self.horizontalLayout_13.addWidget(self.pushButton_clear)
        self.lineEdit_exclude = QtGui.QLineEdit(self.splitter_2)
        self.lineEdit_exclude.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_exclude.setObjectName(_fromUtf8("lineEdit_exclude"))
        self.commandLinkButton_save = QtGui.QCommandLinkButton(self.splitter_2)
        self.commandLinkButton_save.setEnabled(False)
        self.commandLinkButton_save.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setBold(True)
        font.setWeight(75)
        self.commandLinkButton_save.setFont(font)
        self.commandLinkButton_save.setObjectName(_fromUtf8("commandLinkButton_save"))
        self.verticalLayout_2.addWidget(self.splitter_2)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.widget_preview = QtGui.QWidget(FormDTIQA)
        self.widget_preview.setObjectName(_fromUtf8("widget_preview"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.widget_preview)
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout_preview_xy = QtGui.QVBoxLayout()
        self.verticalLayout_preview_xy.setObjectName(_fromUtf8("verticalLayout_preview_xy"))
        self.widget_preview_xy = QtGui.QWidget(self.widget_preview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_preview_xy.sizePolicy().hasHeightForWidth())
        self.widget_preview_xy.setSizePolicy(sizePolicy)
        self.widget_preview_xy.setMinimumSize(QtCore.QSize(256, 256))
        self.widget_preview_xy.setObjectName(_fromUtf8("widget_preview_xy"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.widget_preview_xy)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_preview_xy = PreviewQLabel(self.widget_preview_xy, slicing_axis='z')
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_preview_xy.sizePolicy().hasHeightForWidth())
        self.label_preview_xy.setSizePolicy(sizePolicy)
        self.label_preview_xy.setMaximumSize(QtCore.QSize(256, 256))
        self.label_preview_xy.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.label_preview_xy.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_preview_xy.setFrameShadow(QtGui.QFrame.Plain)
        self.label_preview_xy.setText(_fromUtf8(""))
        self.label_preview_xy.setAlignment(QtCore.Qt.AlignCenter)
        self.label_preview_xy.setObjectName(_fromUtf8("label_preview_xy"))
        self.horizontalLayout_7.addWidget(self.label_preview_xy)
        self.verticalLayout_preview_xy.addWidget(self.widget_preview_xy)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalSlider_z = QtGui.QSlider(self.widget_preview)
        self.horizontalSlider_z.setEnabled(False)
        self.horizontalSlider_z.setMaximumSize(QtCore.QSize(16777215, 30))
        self.horizontalSlider_z.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_z.setObjectName(_fromUtf8("horizontalSlider_z"))
        self.horizontalLayout_6.addWidget(self.horizontalSlider_z)
        self.lcdNumber_z = QtGui.QLCDNumber(self.widget_preview)
        self.lcdNumber_z.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_z.sizePolicy().hasHeightForWidth())
        self.lcdNumber_z.setSizePolicy(sizePolicy)
        self.lcdNumber_z.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lcdNumber_z.setObjectName(_fromUtf8("lcdNumber_z"))
        self.horizontalLayout_6.addWidget(self.lcdNumber_z)
        self.checkBox_preview_xy_vflip = QtGui.QCheckBox(self.widget_preview)
        self.checkBox_preview_xy_vflip.setEnabled(False)
        self.checkBox_preview_xy_vflip.setObjectName(_fromUtf8("checkBox_preview_xy_vflip"))
        self.horizontalLayout_6.addWidget(self.checkBox_preview_xy_vflip)
        self.checkBox_preview_xy_hflip = QtGui.QCheckBox(self.widget_preview)
        self.checkBox_preview_xy_hflip.setEnabled(False)
        self.checkBox_preview_xy_hflip.setObjectName(_fromUtf8("checkBox_preview_xy_hflip"))
        self.horizontalLayout_6.addWidget(self.checkBox_preview_xy_hflip)
        self.verticalLayout_preview_xy.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_11.addLayout(self.verticalLayout_preview_xy)
        self.verticalLayout_preview_yz = QtGui.QVBoxLayout()
        self.verticalLayout_preview_yz.setObjectName(_fromUtf8("verticalLayout_preview_yz"))
        self.widget_preview_yz = QtGui.QWidget(self.widget_preview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_preview_yz.sizePolicy().hasHeightForWidth())
        self.widget_preview_yz.setSizePolicy(sizePolicy)
        self.widget_preview_yz.setMinimumSize(QtCore.QSize(256, 256))
        self.widget_preview_yz.setObjectName(_fromUtf8("widget_preview_yz"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widget_preview_yz)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_preview_yz = PreviewQLabel(self.widget_preview_yz, slicing_axis='x')
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_preview_yz.sizePolicy().hasHeightForWidth())
        self.label_preview_yz.setSizePolicy(sizePolicy)
        self.label_preview_yz.setMaximumSize(QtCore.QSize(256, 256))
        self.label_preview_yz.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.label_preview_yz.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_preview_yz.setText(_fromUtf8(""))
        self.label_preview_yz.setAlignment(QtCore.Qt.AlignCenter)
        self.label_preview_yz.setObjectName(_fromUtf8("label_preview_yz"))
        self.horizontalLayout_8.addWidget(self.label_preview_yz)
        self.verticalLayout_preview_yz.addWidget(self.widget_preview_yz)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.horizontalSlider_x = QtGui.QSlider(self.widget_preview)
        self.horizontalSlider_x.setEnabled(False)
        self.horizontalSlider_x.setMaximumSize(QtCore.QSize(16777215, 30))
        self.horizontalSlider_x.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_x.setObjectName(_fromUtf8("horizontalSlider_x"))
        self.horizontalLayout_10.addWidget(self.horizontalSlider_x)
        self.lcdNumber_x = QtGui.QLCDNumber(self.widget_preview)
        self.lcdNumber_x.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_x.sizePolicy().hasHeightForWidth())
        self.lcdNumber_x.setSizePolicy(sizePolicy)
        self.lcdNumber_x.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lcdNumber_x.setObjectName(_fromUtf8("lcdNumber_x"))
        self.horizontalLayout_10.addWidget(self.lcdNumber_x)
        self.checkBox_preview_yz_vflip = QtGui.QCheckBox(self.widget_preview)
        self.checkBox_preview_yz_vflip.setEnabled(False)
        self.checkBox_preview_yz_vflip.setObjectName(_fromUtf8("checkBox_preview_yz_vflip"))
        self.horizontalLayout_10.addWidget(self.checkBox_preview_yz_vflip)
        self.checkBox_preview_yz_hflip = QtGui.QCheckBox(self.widget_preview)
        self.checkBox_preview_yz_hflip.setEnabled(False)
        self.checkBox_preview_yz_hflip.setObjectName(_fromUtf8("checkBox_preview_yz_hflip"))
        self.horizontalLayout_10.addWidget(self.checkBox_preview_yz_hflip)
        self.checkBox_preview_yz_rotate = QtGui.QCheckBox(self.widget_preview)
        self.checkBox_preview_yz_rotate.setEnabled(False)
        self.checkBox_preview_yz_rotate.setObjectName(_fromUtf8("checkBox_preview_yz_rotate"))
        self.horizontalLayout_10.addWidget(self.checkBox_preview_yz_rotate)
        self.verticalLayout_preview_yz.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11.addLayout(self.verticalLayout_preview_yz)
        self.verticalLayout_preview_zx = QtGui.QVBoxLayout()
        self.verticalLayout_preview_zx.setObjectName(_fromUtf8("verticalLayout_preview_zx"))
        self.widget_preview_zx = QtGui.QWidget(self.widget_preview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_preview_zx.sizePolicy().hasHeightForWidth())
        self.widget_preview_zx.setSizePolicy(sizePolicy)
        self.widget_preview_zx.setMinimumSize(QtCore.QSize(256, 256))
        self.widget_preview_zx.setObjectName(_fromUtf8("widget_preview_zx"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.widget_preview_zx)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_preview_zx = PreviewQLabel(self.widget_preview_zx, slicing_axis='y')
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_preview_zx.sizePolicy().hasHeightForWidth())
        self.label_preview_zx.setSizePolicy(sizePolicy)
        self.label_preview_zx.setMaximumSize(QtCore.QSize(256, 256))
        self.label_preview_zx.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.label_preview_zx.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_preview_zx.setText(_fromUtf8(""))
        self.label_preview_zx.setAlignment(QtCore.Qt.AlignCenter)
        self.label_preview_zx.setObjectName(_fromUtf8("label_preview_zx"))
        self.horizontalLayout_12.addWidget(self.label_preview_zx)
        self.verticalLayout_preview_zx.addWidget(self.widget_preview_zx)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.horizontalSlider_y = QtGui.QSlider(self.widget_preview)
        self.horizontalSlider_y.setEnabled(False)
        self.horizontalSlider_y.setMaximumSize(QtCore.QSize(16777215, 30))
        self.horizontalSlider_y.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_y.setObjectName(_fromUtf8("horizontalSlider_y"))
        self.horizontalLayout_9.addWidget(self.horizontalSlider_y)
        self.lcdNumber_y = QtGui.QLCDNumber(self.widget_preview)
        self.lcdNumber_y.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_y.sizePolicy().hasHeightForWidth())
        self.lcdNumber_y.setSizePolicy(sizePolicy)
        self.lcdNumber_y.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lcdNumber_y.setObjectName(_fromUtf8("lcdNumber_y"))
        self.horizontalLayout_9.addWidget(self.lcdNumber_y)
        self.checkBox_preview_zx_vflip = QtGui.QCheckBox(self.widget_preview)
        self.checkBox_preview_zx_vflip.setEnabled(False)
        self.checkBox_preview_zx_vflip.setObjectName(_fromUtf8("checkBox_preview_zx_vflip"))
        self.horizontalLayout_9.addWidget(self.checkBox_preview_zx_vflip)
        self.checkBox_preview_zx_hflip = QtGui.QCheckBox(self.widget_preview)
        self.checkBox_preview_zx_hflip.setEnabled(False)
        self.checkBox_preview_zx_hflip.setObjectName(_fromUtf8("checkBox_preview_zx_hflip"))
        self.horizontalLayout_9.addWidget(self.checkBox_preview_zx_hflip)
        self.checkBox_preview_zx_rotate = QtGui.QCheckBox(self.widget_preview)
        self.checkBox_preview_zx_rotate.setEnabled(False)
        self.checkBox_preview_zx_rotate.setObjectName(_fromUtf8("checkBox_preview_zx_rotate"))
        self.horizontalLayout_9.addWidget(self.checkBox_preview_zx_rotate)
        self.verticalLayout_preview_zx.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11.addLayout(self.verticalLayout_preview_zx)
        self.gridLayout.addWidget(self.widget_preview, 1, 0, 1, 1)

        self.retranslateUi(FormDTIQA)
        QtCore.QObject.connect(self.horizontalSlider_z, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_z.display)
        QtCore.QObject.connect(self.horizontalSlider_x, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_x.display)
        QtCore.QObject.connect(self.horizontalSlider_y, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_y.display)
        QtCore.QObject.connect(self.horizontalSlider_imageno, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_imageno.display)
        QtCore.QMetaObject.connectSlotsByName(FormDTIQA)

    def retranslateUi(self, FormDTIQA):
        FormDTIQA.setWindowTitle(_translate("FormDTIQA", "DTI Quality Control GUI", None))
        self.label_nifti.setText(_translate("FormDTIQA", "DTI nifti", None))
        self.pushButton_nifti.setText(_translate("FormDTIQA", "browse", None))
        self.label_bvals.setText(_translate("FormDTIQA", "bvals", None))
        self.pushButton_bvals.setText(_translate("FormDTIQA", "browse", None))
        self.label_bvecs.setText(_translate("FormDTIQA", "bvecs", None))
        self.pushButton_bvecs.setText(_translate("FormDTIQA", "browse", None))
        self.label_loadedpath.setText(_translate("FormDTIQA", "Dataset", None))
        self.commandLinkButton_load.setToolTip(_translate("FormDTIQA", "click to load dataset", None))
        self.commandLinkButton_load.setText(_translate("FormDTIQA", "load dataset", None))
        self.label_bvaluetitle.setText(_translate("FormDTIQA", "b-value:", None))
        self.pushButton_exclude.setToolTip(_translate("FormDTIQA", "exclude current direction", None))
        self.pushButton_exclude.setText(_translate("FormDTIQA", "(e)xclude", None))
        self.pushButton_clear.setToolTip(_translate("FormDTIQA", "clear selected directions", None))
        self.pushButton_clear.setText(_translate("FormDTIQA", "clear", None))
        self.lineEdit_exclude.setToolTip(_translate("FormDTIQA", "directions to be excluded", None))
        self.commandLinkButton_save.setToolTip(_translate("FormDTIQA", "click to save data excluding selected directions", None))
        self.commandLinkButton_save.setText(_translate("FormDTIQA", "save new dataset", None))
        self.checkBox_preview_xy_vflip.setToolTip(_translate("FormDTIQA", "flip image", None))
        self.checkBox_preview_xy_vflip.setText(_translate("FormDTIQA", "vertical", None))
        self.checkBox_preview_xy_hflip.setToolTip(_translate("FormDTIQA", "flip image", None))
        self.checkBox_preview_xy_hflip.setText(_translate("FormDTIQA", "horizontal", None))
        self.checkBox_preview_yz_vflip.setToolTip(_translate("FormDTIQA", "flip image", None))
        self.checkBox_preview_yz_vflip.setText(_translate("FormDTIQA", "vertical", None))
        self.checkBox_preview_yz_hflip.setToolTip(_translate("FormDTIQA", "flip image", None))
        self.checkBox_preview_yz_hflip.setText(_translate("FormDTIQA", "horizontal", None))
        self.checkBox_preview_yz_rotate.setToolTip(_translate("FormDTIQA", "rotate image", None))
        self.checkBox_preview_yz_rotate.setStatusTip(_translate("FormDTIQA", "rotate by 90 degreesS", None))
        self.checkBox_preview_yz_rotate.setText(_translate("FormDTIQA", "90", None))
        self.checkBox_preview_zx_vflip.setToolTip(_translate("FormDTIQA", "flip image", None))
        self.checkBox_preview_zx_vflip.setText(_translate("FormDTIQA", "vertical", None))
        self.checkBox_preview_zx_hflip.setToolTip(_translate("FormDTIQA", "flip imageS", None))
        self.checkBox_preview_zx_hflip.setText(_translate("FormDTIQA", "horizontal", None))
        self.checkBox_preview_zx_rotate.setToolTip(_translate("FormDTIQA", "rotate image", None))
        self.checkBox_preview_zx_rotate.setStatusTip(_translate("FormDTIQA", "rotate by 90 degreesS", None))
        self.checkBox_preview_zx_rotate.setText(_translate("FormDTIQA", "90", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    FormDTIQA = QtGui.QWidget()
    ui = Ui_FormDTIQA()
    ui.setupUi(FormDTIQA)
    FormDTIQA.show()
    sys.exit(app.exec_())

